### ISSUE TITLE
Layout is messed up when using in XIB.

### ISSUE THREAD

**Issue by LYluyu** [JayantBadlani/ScreenShield#1]
When my controller is loaded using XIB, the layout appears incorrect.

https://github.com/JayantBadlani/ScreenShield/assets/16254669/1776358c-a6c1-41e4-a899-aed881d9bc07

**Comment by JayantBadlani** [comment]
Hello @LYluyu ,

Preventing screen capture in an iOS app is challenging because it's not directly supported by the iOS operating system. In this library, we have customised our code and applied some hacks/workarounds to achieve the desired result. The issue of a messed-up UI is a known problem.

To address the layout issue, consider adding "ScreenShield" protection to your view after the UI finishes loading. Applying "ScreenShield" protection in the **viewDidAppear** method can help mitigate layout problems.
